Repository CamilaRedondo/API-FATEC-3-SEM, pull requests merged in 2023-03, with the labels that each got.

#8 Adding the initial codes of the service that will consume the endpoints
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/db/dbconfig.ts
  backend/src/model/User.ts
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/useCases/user/CreateUser/CreateUserController.ts
  backend/src/useCases/user/CreateUser/CreateUserUC.ts
  backend/src/useCases/user/CreateUser/ICreateUserDTO.ts
  frontend/src/model/classes/User.tsx
  frontend/src/model/interfaces/AuthenticationCredentials.tsx
  frontend/src/model/interfaces/UpdateUserParams.tsx
  frontend/src/services/DataService/DataService.tsx
Labels: enhancement

#22 User/Auth routes and log-in authentication implemented
  backend/.env.example
  backend/package-lock.json
  backend/src/app.ts
  backend/src/db/dbconfig.ts
  backend/src/repositories/ILoginRepository.ts
  backend/src/repositories/IUserRepository.ts
  backend/src/repositories/README.md
  backend/src/repositories/implementation/LoginRepository.ts
  backend/src/repositories/implementation/README.md
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/repositories/implementations/README.md
  backend/src/routes/AuthRoutes.ts
  backend/src/routes/README.md
  backend/src/routes/UserRoutes.ts
  backend/src/server.ts
  backend/src/useCases/README.md
  backend/src/useCases/auth/Login/ILoginDTO.ts
  backend/src/useCases/auth/Login/Login.ts
  backend/src/useCases/auth/Login/LoginController.ts
  backend/src/useCases/auth/Login/LoginUC.ts
  backend/src/useCases/user/DeleteUser/DeleteUser.ts
  backend/src/useCases/user/DeleteUser/DeleteUserController.ts
  backend/src/useCases/user/DeleteUser/DeleteUserUC.ts
  backend/src/useCases/user/DeleteUser/IDeleteUserDTO.ts
  backend/src/useCases/user/FindUserByCpfCnpj/FindUserByCpfCnpj.ts
  backend/src/useCases/user/FindUserByCpfCnpj/FindUserByCpfCnpjController.ts
  backend/src/useCases/user/FindUserByCpfCnpj/FindUserByCpfCnpjUC.ts
  backend/src/useCases/user/FindUserByCpfCnpj/IFindUserByCpfCnpjDTO.ts
  backend/src/useCases/user/FindUserByEmail/FindUserByEmail.ts
  backend/src/useCases/user/FindUserByEmail/FindUserByEmailController.ts
  backend/src/useCases/user/FindUserByEmail/FindUserByEmailUC.ts
  backend/src/useCases/user/FindUserByEmail/IFindUserByEmailDTO.ts
  backend/src/useCases/user/FindUserByFullName/FindUserByFullName.ts
  backend/src/useCases/user/FindUserByFullName/FindUserByFullNameController.ts
  backend/src/useCases/user/FindUserByFullName/FindUserByFullNameUC.ts
  backend/src/useCases/user/FindUserByFullName/IFindUserByFullNameDTO.ts
  backend/src/useCases/user/FindUserByUserName/FindUserByUserName.ts
  backend/src/useCases/user/FindUserByUserName/FindUserByUserNameController.ts
  backend/src/useCases/user/FindUserByUserName/FindUserByUserNameUC.ts
  backend/src/useCases/user/FindUserByUserName/IFindUserByUserNameDTO.ts
Labels: enhancement

#24 Criando rota "FindById" e função "getById".
  backend/README.md
  backend/package-lock.json
  backend/src/repositories/IUserRepository.ts
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/routes/UserRoutes.ts
  backend/src/useCases/user/FindById/FindById.ts
  backend/src/useCases/user/FindById/FindByIdController.ts
  backend/src/useCases/user/FindById/FindByIdDTO.ts
  backend/src/useCases/user/FindById/IFindByIdUC.ts
  frontend/src/services/DataService/DataService.tsx
Labels: bug

#26 Adding dashboard table and fixes in DataService
  frontend/src/model/classes/User.ts
  frontend/src/modules/Content/Content.tsx
  frontend/src/modules/Table/Table.module.css
  frontend/src/modules/Table/Table.tsx
  frontend/src/services/DataService/DataService.ts
Labels: bug, enhancement
