Repository CamilaRedondo/API-FATEC-3-SEM, pull requests merged in 2023-04, with the labels that each got.

#31 Patch 1
  README.md
  readme/BPMN.png
  readme/Backlog Sprints.png
  readme/Burndown.png
  readme/Cronograma.png
  readme/Objective.png
  readme/login_dashboard.gif
  readme/povoando_BD.gif
Labels: documentation

#32 renaming cpf usesCases
  README.md
  backend/.env.example
  backend/package-lock.json
  backend/src/model/User.ts
  backend/src/repositories/IUserRepository.ts
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/routes/UserRoutes.ts
  backend/src/useCases/user/FindUserByCpf/FindUserByCpf.ts
  backend/src/useCases/user/FindUserByCpf/FindUserByCpfController.ts
  backend/src/useCases/user/FindUserByCpf/FindUserByCpfUC.ts
  backend/src/useCases/user/FindUserByCpf/IFindUserByCpfDTO.ts
  backend/src/useCases/user/FindUserByCpfCnpj/FindUserByCpfCnpj.ts
  backend/src/useCases/user/FindUserByCpfCnpj/IFindUserByCpfCnpjDTO.ts
  frontend/package-lock.json
  frontend/src/model/classes/User.ts
  frontend/src/modules/Table/Table.tsx
  readme/erro_login.gif
Labels: bug

#33 feat: Refactoring Data Service to DataServiceAPI, and creating the UserService
  README.md
  backend/README.md
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/routes/UserRoutes.ts
  backend/src/useCases/user/CreateUser/CreateUserController.ts
  backend/src/useCases/user/CreateUser/ICreateUserDTO.ts
  frontend/src/model/interfaces/UserResponse.ts
  frontend/src/modules/Table/Table.tsx
  frontend/src/pages/Logon/LogonPage.tsx
  frontend/src/services/DataService/DataService.ts
  frontend/src/services/DataServiceAPI.ts
  frontend/src/services/UserService/UserService.ts
Labels: bug, enhancement

#34 Fixing app and auth layout
  frontend/README.md
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/Layout/App/App.module.css
  frontend/src/Layout/App/App.tsx
  frontend/src/Layout/App/components/Sidebar/Profile/Profile.module.css
  frontend/src/Layout/App/components/Sidebar/Profile/Profile.tsx
  frontend/src/Layout/App/components/Sidebar/Sidebar.module.css
  frontend/src/Layout/App/components/Sidebar/Sidebar.tsx
  frontend/src/Layout/Auth/Auth.module.css
  frontend/src/Layout/Auth/Auth.tsx
  frontend/src/Layout/Auth/components/Header/Header.module.css
  frontend/src/Layout/Auth/components/Header/Header.tsx
  frontend/src/Layout/Auth/components/Illustration/Illustration.module.css
  frontend/src/Layout/Auth/components/Illustration/Illustration.tsx
  frontend/src/assets/Illustration.svg
  frontend/src/components/LoginButton/LoginButton.tsx
  frontend/src/index.tsx
  frontend/src/model/interfaces/AuthenticationCredentials.tsx
  frontend/src/model/interfaces/IAuthenticationCredentials.ts
  frontend/src/model/interfaces/IResponseProps.ts
  frontend/src/model/interfaces/IUpdateUserParams.ts
  frontend/src/modules/Content/Content.module.css
  frontend/src/modules/Content/Content.tsx
  frontend/src/modules/LoginForm/LoginForm.module.css
  frontend/src/modules/LoginForm/LoginForm.tsx
  frontend/src/modules/MainHeader/MainHeader.module.css
  frontend/src/modules/Sidebar/Sidebar.module.css
  frontend/src/modules/Sidebar/Sidebar.tsx
  frontend/src/pages/Logon/LogonPage.module.css
  frontend/src/pages/Logon/LogonPage.tsx
  frontend/src/pages/NotFound/NotFound.module.css
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/dashboard/Dashboard.module.css
  frontend/src/pages/dashboard/Dashboard.tsx
  frontend/src/routes/App.routes.tsx
  frontend/src/services/UserService/UserService.ts
  frontend/src/styles/fonts.css
  frontend/src/styles/global.css
  frontend/src/styles/variables.css
Labels: bug, enhancement

#37 Development
  frontend/src/components/Breadcrumb/Breadcrumb.tsx
  frontend/src/components/Button/Button.module.css
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Header/Header.module.css
  frontend/src/components/Header/Header.tsx
  frontend/src/modules/Navbar/Navbar.tsx
  frontend/src/pages/dashboard/Dashboard.tsx
Labels: bug, enhancement

#39 Adding session and password encryption
  backend/package-lock.json
  backend/package.json
  backend/src/services/TokenService.ts
  backend/src/useCases/auth/Login/LoginController.ts
  backend/src/useCases/auth/Login/LoginUC.ts
  backend/src/useCases/user/CreateUser/CreateUserController.ts
  backend/src/useCases/user/GetAllUser/GetAllUsersController.ts
  frontend/package-lock.json
  frontend/src/Layout/App/App.tsx
  frontend/src/Layout/App/components/Sidebar/Sidebar.tsx
  frontend/src/Layout/Auth/Auth.tsx
  frontend/src/model/interfaces/UserResponse.ts
  frontend/src/pages/Logon/LogonPage.tsx
  frontend/src/services/UserService/UserService.ts
Labels: enhancement

#43 Session, authorization and fix in password encryption
  backend/src/app.ts
  backend/src/model/Profile.ts
  backend/src/model/User.ts
  backend/src/repositories/IUserRepository.ts
  backend/src/repositories/implementation/UserRepository.ts
  backend/src/routes/UserRoutes.ts
  backend/src/routes/utils/CheckToken.ts
  backend/src/services/TokenService.ts
  backend/src/useCases/auth/Login/ILoginDTO.ts
  backend/src/useCases/auth/Login/LoginController.ts
  backend/src/useCases/auth/Login/LoginUC.ts
  backend/src/useCases/user/CreateAdmin/CreateAdmin.ts
  backend/src/useCases/user/CreateAdmin/CreateAdminController.ts
  backend/src/useCases/user/CreateAdmin/CreateAdminUC.ts
  backend/src/useCases/user/CreateAdmin/ICreateAdminDTO.ts
  backend/src/useCases/user/CreateUser/CreateUserUC.ts
  backend/src/useCases/user/GetAllUser/GetAllUsersController.ts
  frontend/src/Layout/App/components/Sidebar/Profile/Profile.tsx
  frontend/src/model/classes/ProfileVM.ts
  frontend/src/model/classes/UserVM.ts
  frontend/src/model/utils/Session.ts
  frontend/src/pages/Logon/LogonPage.tsx
  frontend/src/services/DataServiceAPI.ts
Labels: bug
